[package]
name = "splitguard"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
sysinfo = { version = "0.30", features = ["windows"] }
